def green_light():
    pins.digital_write_pin(DigitalPin.P1, 1)
    basic.show_number(5)
    basic.pause(1000)
    basic.show_number(4)
    basic.pause(1000)
    basic.show_number(3)
    basic.pause(1000)
    basic.show_number(2)
    basic.pause(1000)
    basic.show_number(1)
    basic.pause(1000)
    basic.show_number(0)
    pins.digital_write_pin(DigitalPin.P1, 0)

def on_button_pressed_a():
    pins.digital_write_pin(DigitalPin.P2, 0)
    basic.show_number(3)
    basic.pause(1000)
    basic.show_number(2)
    basic.pause(1000)
    basic.show_number(1)
    basic.pause(1000)
    basic.show_number(0)
    pins.digital_write_pin(DigitalPin.P2, 0)
    pins.digital_write_pin(DigitalPin.P0, 1)
    basic.show_number(8)
    basic.pause(1000)
    basic.show_number(7)
    basic.pause(1000)
    basic.show_number(6)
    basic.pause(1000)
    basic.show_number(5)
    basic.pause(1000)
    basic.show_number(4)
    basic.pause(1000)
    basic.show_number(3)
    basic.pause(1000)
    basic.show_number(2)
    basic.pause(1000)
    basic.show_number(1)
    basic.pause(1000)
    basic.show_number(0)
    pins.digital_write_pin(DigitalPin.P0, 0)
input.on_button_pressed(Button.A, on_button_pressed_a)

def red_light():
    pins.digital_write_pin(DigitalPin.P0, 1)
    basic.show_number(8)
    basic.pause(1000)
    basic.show_number(7)
    basic.pause(1000)
    basic.show_number(6)
    basic.pause(1000)
    basic.show_number(5)
    basic.pause(1000)
    basic.show_number(4)
    basic.pause(1000)
    basic.show_number(3)
    basic.pause(1000)
    basic.show_number(2)
    basic.pause(1000)
    basic.show_number(1)
    basic.pause(1000)
    basic.show_number(0)
    pins.digital_write_pin(DigitalPin.P0, 0)
def yellow_light():
    pins.digital_write_pin(DigitalPin.P2, 1)
    basic.show_number(3)
    basic.pause(1000)
    basic.show_number(2)
    basic.pause(1000)
    basic.show_number(1)
    basic.pause(1000)
    basic.show_number(0)
    pins.digital_write_pin(DigitalPin.P2, 0)

def on_forever():
    pass
basic.forever(on_forever)
